### ISSUE TITLE
Missing examples/tutorial.ipynb

### ISSUE THREAD

**Issue by aaraney** [cheginit/hydrodata#24]
### Description
Its seems examples/tutorial.ipynb which was added on commit 68fe37f has been removed. What are the future plans for examples/ and if you would like me to write something up, do you have features in mind you would like me to showcase?

**Comment by cheginit** [comment]
I moved the tutorial file to the docs folder since it was more of a demonstration of the package's capabilities. I found this awesome package called [nbsphinx](https://nbsphinx.readthedocs.io) that allows for including Jupyter notebooks directly in the documentation rather than converting it to `rst`.

Regarding the showcases, I am thinking to have some interesting exploratory study that uses Hydrodata to get the data but then carries out some analysis on the retrieved data. For example, get precipitation data for a couple of watersheds then compare the flood events frequency. What do you think?

Also, I am planning to use the example directory for this kind of showcases and use [sphinx-gallery](https://sphinx-gallery.github.io) for including it in the documentation.

**Comment by aaraney** [comment]
I like the inclusion in the docs, and great find with nbsphinx, it was trivial to maintain that part of the site because of it. 

Okay, I like that idea. Plus showing the usage of Hydrodata alongside other packages to solve a problem is a really good idea. Having some simplistic examples would in my eyes also be helpful. Maybe use a really common watershed that people use when learning HEC-RAS or SWIM and show the LULC capabilities and then the precipitation visualized vs the IDF curves for that given catchment? 

Excellent, I wholeheartedly support that plan. Having executable examples much like R does with vignettes included in documentation is fantastic.

**Comment by cheginit** [comment]
That's a great idea. These would be very useful for the target users of Hydrodata!

**Comment by cheginit** [comment]
A new folder containing more example notebooks have been added under docs. Please feel free to add more.
