### ISSUE TITLE
`pqdm` & `xlrd` not in setup.cfg.

### ISSUE THREAD

**Issue by kcaylor** [cheginit/hydrodata#32]
`setup.cfg` is missing some libraries. This leads to errors during library import after installation and while running functions.

**Comment by cheginit** [comment]
@kcaylor Thanks for the report. None of the dependencies are in `setup.cfg` since `pip` alone cannot install all the dependencies. In the [installation](https://hydrodata.readthedocs.io/en/latest/installation.html) section of the documentation, you can find all the dependencies that need to be installed either manually (not recommended) or using Conda and the [YAML file](https://github.com/cheginit/hydrodata/blob/master/environment.yml) provided in the repository. 

The most convenient way to install Hydrodata is to load Conda then:
```bash
wget https://raw.githubusercontent.com/cheginit/hydrodata/master/environment.yml
conda env create -f environment.yml
conda activate hydrodata
```
Let me know if you need more information.

**Comment by mroberge** [comment]
Are you sure that you still need Conda for an install? Have you tried it without recently? There have been some improvements to pip lately, and the wheels system really helps. I went to all `pip` installations to make my TravisCI process go more smoothly, and it went well.

**Comment by cheginit** [comment]
@mroberge The main issue with `pip` is installing `GDAL` dependent packages such as `GeoPandas` and the need for installing some extra packages on the system which could be a nightmare when considering cross-platform development. I haven't tried it recently though. Thanks for the heads up I will give it a try.

Travis has an issue with using the `conda-forge` channel so I use the `defaults` channel for setting up Travis. It took a while to figure out the issue but it works smoothly now.

**Comment by cheginit** [comment]
@mroberge I tried `pip` and it works! That's great. I will release the package in both `pypi` and `conda-forge` so users can decide for themselves which version to use. I personally prefer the Conda option since `NumPy` could be orders of magnitude faster when using binaries from Conda. Thanks for your comment.

**Comment by mroberge** [comment]
That's great! I was concerned about GDAL!

**Comment by cheginit** [comment]
@mroberge Just note that I have GDAL installed on my system, so it's possible that it uses the system's GDAL. I am setting up a branch for using only `pip` to check with Travis if it works.

**Comment by cheginit** [comment]
@kcaylor Hydrodata can now be installed using `pip`. You just have to make sure that `libgdal` is installed on your system or your Python env. You can check by running `gdal-config --version`. If it's not installed you can install it from your system package manager for example `libgdal-dev` on Ubuntu or if you're using `Conda` install `libgdal`.

**Comment by cheginit** [comment]
The package is also available on `conda-forge`. I am going to close this issue. Please feel free to re-open if you still have issues installing the pakcage using `pip` of `conda`.
