### ISSUE TITLE
Monthly & annual SSEBop ET available via OPenDAP from USGS THREDDS server

### ISSUE THREAD

**Issue by emiliom** [cheginit/hydrodata#35]
Re: https://github.com/cheginit/hydrodata/blob/master/hydrodata/datasets.py#L854
> Since there's still no web service available for subsetting SSEBop, the data first
    needs to be downloaded for the requested period then it is masked by the
    region of interest locally. Therefore, it's not as fast as other functions and
    the bottleneck could be the download speed.

FYI, there is an OPeNDAP endpoint available from the USGS CIDA THREDDS server (managed by David Blodgett, I think) for monthly and annual SSEBop ET -- though not daily:

- THREDDS catalog page for monthly data: https://cida.usgs.gov/thredds/catalog.html?dataset=cida.usgs.gov/ssebopeta/monthly
- THREDDS OPeNDAP endpoint: https://cida.usgs.gov/thredds/dodsC/ssebopeta/monthly

**Comment by cheginit** [comment]
@emiliom Thanks for the information. The reason I didn't include them was exactly what you mentioned; it's not daily. Since Daymet (and consequently PET) is daily so I wanted to provide access to the daily data for actual ET so it can be added as a new variable to the output `xarray.Dataset`.

But if there's any need and/or request for adding the monthly and annual data for this dataset, we can add it to Hydrodata.

**Comment by emiliom** [comment]
No specific need; just wanted to mention it in case you weren't aware of it.

**Comment by cheginit** [comment]
Thanks. CIDA offers some very useful datasets.

**Comment by cheginit** [comment]
I will close this. Please feel free to re-open if you want this database to be included in Hydrodata. Thanks.
